services:
  - type: web
    name: websocket-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python websocket_server.py
    envVars:
      - key: PORT
        value: 8002
