services:
  - name: websocket-server
    type: web
    runtime: python
    plan: free
    envVars:
      - key: PORT
        value: 8080
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python websocket_server.py"
