services:
  - name: websocket-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python websocket_server.py
    envVars:
      - key: PORT
        value: "10000"
